// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  systemPrompt: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  version: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  baseUrl: __t.string(),
  respondsToAgents: __t.bool(),
  avatarEmoji: __t.string(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentCard = __t.object("AgentCard", {
  threadId: __t.u64(),
  agentId: __t.u64(),
  name: __t.string(),
  avatarEmoji: __t.string(),
});
export type AgentCard = __Infer<typeof AgentCard>;

export const AgentTurn = __t.object("AgentTurn", {
  id: __t.u64(),
  episodeId: __t.u64(),
  agentId: __t.u64(),
});
export type AgentTurn = __Infer<typeof AgentTurn>;

export const Episode = __t.object("Episode", {
  id: __t.u64(),
  threadId: __t.u64(),
  rootMessageId: __t.u64(),
  turnsRemaining: __t.u8(),
  tokenBudgetRemaining: __t.u64(),
  openedAt: __t.timestamp(),
  status: __t.string(),
});
export type Episode = __Infer<typeof Episode>;

export const Mention = __t.object("Mention", {
  kind: __t.string(),
  ref: __t.u64(),
  start: __t.u32(),
  len: __t.u32(),
});
export type Mention = __Infer<typeof Mention>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  threadId: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  sent: __t.timestamp(),
  streamState: __t.string(),
  runId: __t.string(),
  get mentions() {
    return __t.array(Mention);
  },
  agentId: __t.u64(),
  episodeId: __t.u64(),
});
export type Message = __Infer<typeof Message>;

export const MyActivePersonas = __t.object("MyActivePersonas", {});
export type MyActivePersonas = __Infer<typeof MyActivePersonas>;

export const MyAgents = __t.object("MyAgents", {});
export type MyAgents = __Infer<typeof MyAgents>;

export const MyPersonaKeys = __t.object("MyPersonaKeys", {});
export type MyPersonaKeys = __Infer<typeof MyPersonaKeys>;

export const MyProviderKeys = __t.object("MyProviderKeys", {});
export type MyProviderKeys = __Infer<typeof MyProviderKeys>;

export const MyReplyDeltas = __t.object("MyReplyDeltas", {});
export type MyReplyDeltas = __Infer<typeof MyReplyDeltas>;

export const MyThreadAgents = __t.object("MyThreadAgents", {});
export type MyThreadAgents = __Infer<typeof MyThreadAgents>;

export const MyThreadMembers = __t.object("MyThreadMembers", {});
export type MyThreadMembers = __Infer<typeof MyThreadMembers>;

export const MyThreadMessages = __t.object("MyThreadMessages", {});
export type MyThreadMessages = __Infer<typeof MyThreadMessages>;

export const MyThreads = __t.object("MyThreads", {});
export type MyThreads = __Infer<typeof MyThreads>;

export const ProviderKey = __t.object("ProviderKey", {
  id: __t.u64(),
  owner: __t.identity(),
  provider: __t.string(),
  sealed: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ProviderKey = __Infer<typeof ProviderKey>;

export const ReaperSchedule = __t.object("ReaperSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ReaperSchedule = __Infer<typeof ReaperSchedule>;

export const ReplyDelta = __t.object("ReplyDelta", {
  id: __t.u64(),
  runId: __t.string(),
  threadId: __t.u64(),
  seq: __t.u64(),
  text: __t.string(),
  sent: __t.timestamp(),
});
export type ReplyDelta = __Infer<typeof ReplyDelta>;

export const Run = __t.object("Run", {
  id: __t.u64(),
  runId: __t.string(),
  threadId: __t.u64(),
  agent: __t.identity(),
  model: __t.string(),
  status: __t.string(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  startedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  agentId: __t.u64(),
  episodeId: __t.u64(),
});
export type Run = __Infer<typeof Run>;

export const Service = __t.object("Service", {
  id: __t.u8(),
  identity: __t.identity(),
  encPubKey: __t.string(),
});
export type Service = __Infer<typeof Service>;

export const ServiceInfo = __t.object("ServiceInfo", {});
export type ServiceInfo = __Infer<typeof ServiceInfo>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  kind: __t.string(),
  title: __t.option(__t.string()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  agentId: __t.u64(),
});
export type Thread = __Infer<typeof Thread>;

export const ThreadAgent = __t.object("ThreadAgent", {
  id: __t.u64(),
  threadId: __t.u64(),
  agentId: __t.u64(),
  isDefaultResponder: __t.bool(),
  addedBy: __t.identity(),
  addedAt: __t.timestamp(),
});
export type ThreadAgent = __Infer<typeof ThreadAgent>;

export const ThreadAgentCards = __t.object("ThreadAgentCards", {});
export type ThreadAgentCards = __Infer<typeof ThreadAgentCards>;

export const ThreadMember = __t.object("ThreadMember", {
  id: __t.u64(),
  threadId: __t.u64(),
  member: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type ThreadMember = __Infer<typeof ThreadMember>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

