// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  agentId: __t.u64(),
  name: __t.string(),
  systemPrompt: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  baseUrl: __t.string(),
  respondsToAgents: __t.bool(),
  avatarEmoji: __t.string(),
};
