// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddMemberReducer from "../add_member_reducer";
import AgentReplyAppendReducer from "../agent_reply_append_reducer";
import AgentReplyBeginReducer from "../agent_reply_begin_reducer";
import AgentReplyFinishReducer from "../agent_reply_finish_reducer";
import CreateAgentReducer from "../create_agent_reducer";
import CreateAgentDmReducer from "../create_agent_dm_reducer";
import CreateDmReducer from "../create_dm_reducer";
import CreateGroupReducer from "../create_group_reducer";
import DeleteAgentReducer from "../delete_agent_reducer";
import DeleteProviderKeyReducer from "../delete_provider_key_reducer";
import LeaveThreadReducer from "../leave_thread_reducer";
import RegisterServiceReducer from "../register_service_reducer";
import RemoveMemberReducer from "../remove_member_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SetProviderKeyReducer from "../set_provider_key_reducer";
import SetThreadTitleReducer from "../set_thread_title_reducer";
import UpdateAgentReducer from "../update_agent_reducer";

export type AddMemberParams = __Infer<typeof AddMemberReducer>;
export type AgentReplyAppendParams = __Infer<typeof AgentReplyAppendReducer>;
export type AgentReplyBeginParams = __Infer<typeof AgentReplyBeginReducer>;
export type AgentReplyFinishParams = __Infer<typeof AgentReplyFinishReducer>;
export type CreateAgentParams = __Infer<typeof CreateAgentReducer>;
export type CreateAgentDmParams = __Infer<typeof CreateAgentDmReducer>;
export type CreateDmParams = __Infer<typeof CreateDmReducer>;
export type CreateGroupParams = __Infer<typeof CreateGroupReducer>;
export type DeleteAgentParams = __Infer<typeof DeleteAgentReducer>;
export type DeleteProviderKeyParams = __Infer<typeof DeleteProviderKeyReducer>;
export type LeaveThreadParams = __Infer<typeof LeaveThreadReducer>;
export type RegisterServiceParams = __Infer<typeof RegisterServiceReducer>;
export type RemoveMemberParams = __Infer<typeof RemoveMemberReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SetProviderKeyParams = __Infer<typeof SetProviderKeyReducer>;
export type SetThreadTitleParams = __Infer<typeof SetThreadTitleReducer>;
export type UpdateAgentParams = __Infer<typeof UpdateAgentReducer>;

