// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Message = __t.object("Message", {
  id: __t.u64(),
  threadId: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  sent: __t.timestamp(),
  streamState: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const MyThreadMembers = __t.object("MyThreadMembers", {});
export type MyThreadMembers = __Infer<typeof MyThreadMembers>;

export const MyThreadMessages = __t.object("MyThreadMessages", {});
export type MyThreadMessages = __Infer<typeof MyThreadMessages>;

export const MyThreads = __t.object("MyThreads", {});
export type MyThreads = __Infer<typeof MyThreads>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  kind: __t.string(),
  title: __t.option(__t.string()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Thread = __Infer<typeof Thread>;

export const ThreadMember = __t.object("ThreadMember", {
  id: __t.u64(),
  threadId: __t.u64(),
  member: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type ThreadMember = __Infer<typeof ThreadMember>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

