// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Mention,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  threadId: __t.u64().name("thread_id"),
  sender: __t.identity(),
  text: __t.string(),
  sent: __t.timestamp(),
  streamState: __t.string().name("stream_state"),
  runId: __t.string().name("run_id"),
  get mentions() {
    return __t.array(Mention);
  },
  agentId: __t.u64().name("agent_id"),
  episodeId: __t.u64().name("episode_id"),
});
