// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  systemPrompt: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  version: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  threadId: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  sent: __t.timestamp(),
  streamState: __t.string(),
  runId: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const MyActivePersonas = __t.object("MyActivePersonas", {});
export type MyActivePersonas = __Infer<typeof MyActivePersonas>;

export const MyAgents = __t.object("MyAgents", {});
export type MyAgents = __Infer<typeof MyAgents>;

export const MyPersonaKeys = __t.object("MyPersonaKeys", {});
export type MyPersonaKeys = __Infer<typeof MyPersonaKeys>;

export const MyProviderKeys = __t.object("MyProviderKeys", {});
export type MyProviderKeys = __Infer<typeof MyProviderKeys>;

export const MyThreadMembers = __t.object("MyThreadMembers", {});
export type MyThreadMembers = __Infer<typeof MyThreadMembers>;

export const MyThreadMessages = __t.object("MyThreadMessages", {});
export type MyThreadMessages = __Infer<typeof MyThreadMessages>;

export const MyThreads = __t.object("MyThreads", {});
export type MyThreads = __Infer<typeof MyThreads>;

export const ProviderKey = __t.object("ProviderKey", {
  id: __t.u64(),
  owner: __t.identity(),
  provider: __t.string(),
  sealed: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ProviderKey = __Infer<typeof ProviderKey>;

export const Run = __t.object("Run", {
  id: __t.u64(),
  runId: __t.string(),
  threadId: __t.u64(),
  agent: __t.identity(),
  model: __t.string(),
  status: __t.string(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  startedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Run = __Infer<typeof Run>;

export const Service = __t.object("Service", {
  id: __t.u8(),
  identity: __t.identity(),
  encPubKey: __t.string(),
});
export type Service = __Infer<typeof Service>;

export const ServiceInfo = __t.object("ServiceInfo", {});
export type ServiceInfo = __Infer<typeof ServiceInfo>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  kind: __t.string(),
  title: __t.option(__t.string()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  agentId: __t.u64(),
});
export type Thread = __Infer<typeof Thread>;

export const ThreadMember = __t.object("ThreadMember", {
  id: __t.u64(),
  threadId: __t.u64(),
  member: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type ThreadMember = __Infer<typeof ThreadMember>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

